Remove upper limit for jedi version.
The allowed version of jedi was limited from above by 0.20 (0.19 in the version used by pip). The current limit led to an error while using pip to upgrade my Python packages:
ERROR: python-lsp-server 1.7.4 requires jedi<0.19.0,>=0.17.2, but you have jedi 0.19.0 which is incompatible.

Due to this, it is currently not possible to have a current python-lsp-server package from PyPI and a current jedi package side-by-side without annoying pip errors like the one shown above. 

An approach would be to manually install the debug version, but this solution only postpones the problem up to the next jedi update.

Using git blame, I found no reasons to limit the version in the current version. The restriction by above was introduced in commit 9f0710c (https://github.com/python-lsp/python-lsp-server/commit/9f0710cd942cbd6832632c1f0132c4724be74229) to circumvent a then-current incompatibility. But since then, the limit was only bumped without further comment which showed that the jedi incompatibility wandered to the next jedi version too while having been corrected in the old jedi version.

Therefore, I propose to remove the restriction for being unnecessary and harmful.